# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'
container: ubuntu:18.04
steps:
- task: DownloadSecureFile@1
  name: signingkey
  inputs:
    secureFile: 'signingkey.asc'
- task: DownloadSecureFile@1
  name: signingkey_private
  inputs:
    secureFile: 'signingkey.private.asc'
- script: |-
    apt install gnupg
    gpg --keyring=$HOME/gpg/pubring.gpg --no-default-keyring --batch --import $(signingkey.secureFilePath)
    gpg --keyring=$HOME/gpg/secring.gpg --no-default-keyring --batch --allow-secret-key-import --import $(signingkey_private.secureFilePath)
  displayName: 'Installing gpg2'
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean deploy'
    options: >-
      -P sign
      --settings deployment/settings.xml
      -Dgpg.executable=gpg
      -DskipTests
      -Dgpg.keyname=$(signingkey_id)
      -Dgpg.passphrase=$(signingkey_passphrase)
      -Dgpg.publicKeyring=$HOME/gpg/pubring.gpg
      -Dgpg.secretKeyring=$HOME/gpg/secring.gpg
