# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DownloadSecureFile@1
  name: signingkey_private
  inputs:
    secureFile: 'signingkey.private.gpg'
- task: DownloadSecureFile@1
  name: signingkey
  inputs:
    secureFile: 'signingkey.private.gpg'
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean deploy'
    options: '-P sign --settings deployment/settings.xml -Dgpg.executable=gpg2 -DskipTests -Dgpg.keyname=7F1F5043C210ADFE -Dgpg.passphrase=$(signingkey_passphrase) -Dgpg.publicKeyring=$(signingkey.secureFilePath) -Dgpg.secretKeyring=$(signingkey_private.secureFilePath)'
